export const skillsData = [
  "Node.js",
  "React.js",
  "Next.js",
  "Express.js",
  "MongoDB",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "Spring Boot",
  "Django",
  "Vue.js",
  "Angular",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Sass",
  "Ruby",
  "Rails",
  "Go",
  "PHP",
  "Swift",
  "Kotlin",
  "C#",
  "ASP.NET",
  "MySQL",
  "PostgreSQL",
  "SQLite",
  "Firebase",
  "AWS",
  "Azure",
  "Docker",
  "Kubernetes",
  "GraphQL",
  "REST API",
  "Redux",
  "Android",
  "iOS",
  "Flutter",
  "React Native",
  "Xamarin",
  "Swift (iOS)",
  "Objective-C (iOS)",
  "Dart",
  "UI/UX Design",
  "Adobe XD",
  "Figma",
  "Sketch",
  "Data Science",
  "TensorFlow",
  "PyTorch",
];

export const roles = [
  "Android Developer",
  "Backend Developer",
  "Blockchain Developer",
  "Cloud Developer",
  "Cloud Engineer",
  "Data Scientist",
  "Database Developer",
  "DevOps Engineer",
  "Flutter/React Native Developer",
  "Frontend Developer",
  "Full Stack Developer",
  "Full Stack Developer (MERN)",
  "Full Stack Web Developer",
  "Machine Learning Engineer",
  "Mobile App Developer",
  "UI/UX Designer",
];

export const requiredFields = [
  "fname",
  "lname",
  "email",
  "about",
  "role",
  "github",
  "linkedin",
  "resume",
  "skills"
];

export const requiredFieldsSendOTP = [
  "fname",
  "lname",
  "email",
  "password",
  "confirmPassword",
];